// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0V-Kasme6QBbb4SQOacOhszRNH57T9w0',
    appId: '1:927839094094:android:35da168efbb289d1a8ca1f',
    messagingSenderId: '927839094094',
    projectId: 'guitar-raag-mini-firebase',
    storageBucket: 'guitar-raag-mini-firebase.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqoHWGuyXW_5Rp9i9vIRhIuY8ByAv_sBY',
    appId: '1:927839094094:ios:cb54c748d703034ea8ca1f',
    messagingSenderId: '927839094094',
    projectId: 'guitar-raag-mini-firebase',
    storageBucket: 'guitar-raag-mini-firebase.firebasestorage.app',
    iosBundleId: 'com.collegegtrraag.clgProjectGtrRaag',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqoHWGuyXW_5Rp9i9vIRhIuY8ByAv_sBY',
    appId: '1:927839094094:ios:cb54c748d703034ea8ca1f',
    messagingSenderId: '927839094094',
    projectId: 'guitar-raag-mini-firebase',
    storageBucket: 'guitar-raag-mini-firebase.firebasestorage.app',
    iosBundleId: 'com.collegegtrraag.clgProjectGtrRaag',
  );

}